### PR TITLE
I9t

### PR DESCRIPTION
**Pull request by pietrorea**
iPhone, first draft. Looking for high level feedback. Is this new structure going to be helpful for next year's conference?

### CODE REVIEW

**Comment by rwenderlich** [comment]
Hey Pietro,

I took a peek at this and here's some high level feedback:
- Videos do not appear to play; I get a vimeo error page when trying this.
- The Maps tab seems like a waste for a small conference like us; I suggest removing this.
- I'm not a fan of the "dual tab bar" approach at the bottom of the screen on the Schedule tab. I suggest either moving the segmented control to the top like the WWDC app, or making the bottom tab bar "Friday/Saturday/My Schedule/Videos" (which might look better).
- The scroll view bounds on the video tab don't appear correct. The logo is cut off on top, and on the bottom you can't see the final item in the list.

screen shot 2015-07-08 at 12 15 40 pm
screen shot 2015-07-08 at 12 15 45 pm
- (Nice to have) I'm not sure if re-using the table view list from the schedule tab is the right way to go for the videos. It would be much nicer to have a simple 2-column collection view with thumbnails of each video and the session title underneath, where you tap it once to play.
- (Nice to have) Ability to download videos like WWDC app. We could move the conference videos to a convenient spot to make this happen.

**Comment by sammyd** [comment]
I think that this could work as a great addition to the app. In addition to the comments from Ray:
- The first time I tap the "Videos" tab I have to tap "Back" on the nav controller.
- I agree with Ray about the session controller re-use. A lot of that info is no longer relevant. Since they're inspiration videos, I don't think you need extra info other than the title and the speaker's name. I reckon this could simplify the layout somewhat.
- The reason that the video didn't play was because it was a sample URL. None of the RWDevCon URLs were accessible outside raywenderlich.com. I got Christine to allow wider access on Kim's "Finishing" talk as a test case: https://vimeo.com/130393876
  There seems to be a problem with playing this on the simulator:
  simulator screen shot 8 jul 2015 21 50 43

I could get the link to work on my device. Not too sure about the rendered web page though. Apparently it might be possible to use HTTP streaming directly - I can check this out if you think it'd be an option?

**Comment by pietrorea** [comment]
Hi Ray & Sam,

I’ve updated the PR with your feedback. You may have to delete your local branches and re-pull as I did a force push. Here are some notes:
- The best solution for the videos is to upload them to a domain we control like rw.com or rwdevcon (preferred) and stream them from there. Sam, I tried Kim’s video and it still wouldn’t play. I assume Vimeo doesn’t want any old app creating an unauthorized client. There are hacks to get around this but I wouldn’t go down that path
- I removed the tabs altogether and went with Ray’s suggestion of adding “Videos” to the segmented control. This does look better.
- Scrollview problem is fixed.
- I simplified the session view controller for the archived videos. Now all we have is the description, the presenter and a “Show Video” button.
- Nice to haves: I kept the table view for the list of videos as this would have been a much bigger change. Also, we would be able to download the videos for offline viewing if we moved away from Vimeo.

**Comment by sammyd** [comment]
Hey Pietro,

I think these changes look good - and apart from the video playback itself, I reckon that it looks like a good improvement to the app, and a good demo for what you're going to want to write about in i9t.

(Regarding the video playback, the "Done" button doesn't work).

I'll chat to Ray and get back to you about the video hosting and the other things you mentioned in your email.

**Comment by rwenderlich** [comment]
Hey Pietro,

This is looking much better, thanks for making these mods! 

It's OK to keep with the table view in interest of time, but can you make it just play the video if you tap on it (rather than go to that intermediate page w/ the description, etc)?

We'll work on getting the videos hosted directly on rwdevcon.com for you. Downloads for offline viewing like the WWDC app would be amazing!

**Comment by sammyd** [comment]
@rwenderlich @micpringle 

Just noticed that this PR hasn't been merged in. Should it have been?

**Pull request closed without merging**
